// Robust YouTube caption fetcher (server-side / Vercel).
//
// YouTube exposes captions through several surfaces and any one of them can fail
// for a given video or IP (region walls, consent pages, missing tracks, rate
// limits). So we try a cascade of independent strategies and return the first
// that yields segments. Preference favours auto-generated (ASR) captions, then
// manual, then any available track — better to show original-language captions
// than nothing.
//
// IMPORTANT lessons baked in here (verified empirically, 2025):
//   • The InnerTube ANDROID player API is the reliable source. Its caption
//     `baseUrl`s carry a token that lets them actually download.
//   • Caption text now comes back as srv3 *XML* — appending &fmt=json3 returns
//     an EMPTY body, and so do baseUrls scraped from the watch page HTML.
//   • &tlang= auto-translation also returns empty, so we don't rely on it.
//
// Strategies, in order:
//   1. InnerTube ANDROID  — primary; smart ASR-first track selection
//   2. youtube-transcript  — independent fallback (uses InnerTube internally too)
//   3. Watch-page scrape   — last resort track discovery

import { YoutubeTranscript } from "youtube-transcript";

export type TranscriptSegment = { start: number; duration: number; text: string };

export type CaptionResult = {
  videoId: string;
  languageCode: string;
  isAutoGenerated: boolean;
  segments: TranscriptSegment[];
  strategy: string; // which method succeeded (for diagnostics/logging)
};

// ── InnerTube client config (matches a real ANDROID app request) ────────────
const INNERTUBE_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";
const INNERTUBE_CLIENT_VERSION = "20.10.38";
// Exported: googlevideo CDN format URLs obtained via the ANDROID client must
// be fetched with a matching User-Agent, or they 403 (seen empirically with
// the reference-audio fetch in lib/audio-ref.ts).
export const INNERTUBE_UA = `com.google.android.youtube/${INNERTUBE_CLIENT_VERSION} (Linux; U; Android 14)`;

const BROWSER_UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";
const WATCH_PAGE_HEADERS: Record<string, string> = {
  "User-Agent": BROWSER_UA,
  "Accept-Language": "en-US,en;q=0.9",
  // CONSENT cookie skips the EU consent interstitial that hides the player JSON.
  Cookie: "CONSENT=YES+cb.20210328-17-p0.en+FX+000",
};

type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  kind?: string; // "asr" for auto-generated
};

export type AdaptiveFormat = {
  itag: number;
  mimeType: string;
  bitrate?: number;
  url?: string;
  approxDurationMs?: string;
};

type PlayerResponse = {
  playabilityStatus?: {
    status?: string;
    reason?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
  streamingData?: {
    adaptiveFormats?: AdaptiveFormat[];
  };
};

// Fetches the raw InnerTube ANDROID player response for a video. The ANDROID
// client returns direct (uncipered) format URLs — no signature decryption
// needed, unlike the WEB client. Shared by caption fetching (captions[]) and
// reference-audio extraction (streamingData.adaptiveFormats).
export async function fetchPlayerResponse(videoId: string): Promise<PlayerResponse> {
  const res = await fetch(INNERTUBE_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json", "User-Agent": INNERTUBE_UA },
    body: JSON.stringify({
      context: { client: { clientName: "ANDROID", clientVersion: INNERTUBE_CLIENT_VERSION } },
      videoId,
    }),
  });
  if (!res.ok) throw new Error(`player API HTTP ${res.status}`);

  const data = (await res.json()) as PlayerResponse;
  const status = data?.playabilityStatus?.status;
  if (status && status !== "OK") {
    const reason = data?.playabilityStatus?.reason ?? "";
    throw new Error(`not playable: ${status}${reason ? ` (${reason})` : ""}`);
  }
  return data;
}

// ── Public entry point ──────────────────────────────────────────────────────

// Tries every strategy until one returns segments. Throws an aggregated error
// (listing what each strategy reported) only if ALL of them fail.
export async function fetchCaptions(videoId: string, lang = "en"): Promise<CaptionResult> {
  const strategies: Array<{ name: string; run: () => Promise<CaptionResult> }> = [
    { name: "innertube-android", run: () => viaInnertube(videoId, lang) },
    { name: "npm-youtube-transcript", run: () => viaNpmPackage(videoId, lang) },
    { name: "watch-page", run: () => viaWatchPage(videoId, lang) },
  ];

  const errors: string[] = [];
  for (const { name, run } of strategies) {
    try {
      const result = await run();
      if (result.segments.length > 0) {
        console.log(`[captions] ✓ ${name} → ${result.segments.length} segments`, {
          lang: result.languageCode,
          asr: result.isAutoGenerated,
        });
        return result;
      }
      errors.push(`${name}: returned 0 segments`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.warn(`[captions] ✗ ${name}: ${msg}`);
      errors.push(`${name}: ${msg}`);
    }
  }

  throw new Error(`All caption strategies failed for ${videoId}:\n  - ${errors.join("\n  - ")}`);
}

// ── Shared helpers ──────────────────────────────────────────────────────────

// Picks the best track: ASR in target lang, then manual in target lang, then any
// ASR track, then the first track. Never throws on a missing language — showing
// original-language captions beats showing nothing.
function pickTrack(tracks: CaptionTrack[], lang: string): CaptionTrack {
  return (
    tracks.find((t) => t.kind === "asr" && t.languageCode === lang) ||
    tracks.find((t) => t.kind !== "asr" && t.languageCode === lang) ||
    tracks.find((t) => t.kind === "asr") ||
    tracks[0]
  );
}

// Downloads a caption track and parses its timed text. The baseUrl is fetched
// AS-IS (no &fmt=) because that's the only form that still returns a body.
async function downloadTrack(track: CaptionTrack): Promise<TranscriptSegment[]> {
  const res = await fetch(track.baseUrl, { headers: { "User-Agent": BROWSER_UA } });
  if (!res.ok) throw new Error(`timedtext HTTP ${res.status}`);
  const body = await res.text();
  if (!body.trim()) throw new Error("empty timedtext body (token-gated baseUrl)");
  return parseTimedText(body);
}

// Parses both timed-text shapes YouTube returns:
//   srv3:    <p t="ms" d="ms"><s>word</s>...</p>
//   classic: <text start="sec" dur="sec">line</text>
function parseTimedText(xml: string): TranscriptSegment[] {
  const out: TranscriptSegment[] = [];

  const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let m: RegExpExecArray | null;
  while ((m = pRegex.exec(xml)) !== null) {
    const text = decodeEntities(m[3].replace(/<[^>]+>/g, "")).trim();
    if (text) out.push({ start: Number(m[1]) / 1000, duration: Number(m[2]) / 1000, text });
  }
  if (out.length) return out;

  const textRegex = /<text start="([^"]*)" dur="([^"]*)">([^<]*)<\/text>/g;
  while ((m = textRegex.exec(xml)) !== null) {
    const text = decodeEntities(m[3]).trim();
    if (text) out.push({ start: Number(m[1]), duration: Number(m[2]), text });
  }
  return out;
}

// Decodes XML/HTML entities, handling YouTube's occasional double-encoding
// (&amp;#39;) by resolving &amp; before the numeric/named entities.
function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, n) => String.fromCharCode(parseInt(n, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">");
}

// ── Strategy 1: InnerTube ANDROID player API ────────────────────────────────

async function viaInnertube(videoId: string, lang: string): Promise<CaptionResult> {
  const data = await fetchPlayerResponse(videoId);

  const tracks: CaptionTrack[] | undefined =
    data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks?.length) throw new Error("no caption tracks in player response");

  const track = pickTrack(tracks, lang);
  const segments = await downloadTrack(track);
  return {
    videoId,
    languageCode: track.languageCode,
    isAutoGenerated: track.kind === "asr",
    segments,
    strategy: "innertube-android",
  };
}

// ── Strategy 2: youtube-transcript npm package ──────────────────────────────

async function viaNpmPackage(videoId: string, lang: string): Promise<CaptionResult> {
  // Try the requested language; if the package throws (e.g. that exact language
  // isn't available), retry with no language so it picks the default track.
  const raw = await YoutubeTranscript.fetchTranscript(videoId, { lang }).catch(() =>
    YoutubeTranscript.fetchTranscript(videoId),
  );
  // The package returns offset/duration in MILLISECONDS.
  const segments: TranscriptSegment[] = raw.map((item) => ({
    start: item.offset / 1000,
    duration: item.duration / 1000,
    text: item.text,
  }));
  return {
    videoId,
    languageCode: lang,
    isAutoGenerated: false, // package doesn't report this
    segments,
    strategy: "npm-youtube-transcript",
  };
}

// ── Strategy 3: scrape ytInitialPlayerResponse from the watch page ──────────

async function viaWatchPage(videoId: string, lang: string): Promise<CaptionResult> {
  const res = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: WATCH_PAGE_HEADERS,
  });
  if (!res.ok) throw new Error(`watch page HTTP ${res.status}`);
  const html = await res.text();
  if (html.includes('class="g-recaptcha"')) throw new Error("rate-limited (captcha wall)");

  const player = extractPlayerResponse(html);
  if (!player) throw new Error("could not parse ytInitialPlayerResponse");

  const tracks: CaptionTrack[] | undefined =
    player?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks?.length) throw new Error("no caption tracks on watch page");

  const track = pickTrack(tracks, lang);
  const segments = await downloadTrack(track);
  return {
    videoId,
    languageCode: track.languageCode,
    isAutoGenerated: track.kind === "asr",
    segments,
    strategy: "watch-page",
  };
}

// Extracts the ytInitialPlayerResponse object via brace-balanced slicing
// (a non-greedy regex truncates on the first "}" inside the huge JSON blob).
function extractPlayerResponse(html: string): PlayerResponse | null {
  for (const marker of ["ytInitialPlayerResponse =", "ytInitialPlayerResponse="]) {
    const at = html.indexOf(marker);
    if (at === -1) continue;
    const start = html.indexOf("{", at);
    if (start === -1) continue;
    const json = sliceBalancedJson(html, start);
    if (!json) continue;
    try {
      return JSON.parse(json);
    } catch {
      // try the next marker
    }
  }
  return null;
}

// Returns the substring from `start` (a "{") through its matching "}",
// correctly skipping braces inside string literals.
function sliceBalancedJson(str: string, start: number): string | null {
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < str.length; i++) {
    const ch = str[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return str.slice(start, i + 1);
    }
  }
  return null;
}
